--GRUPO 11
--Josué David Pérez Pérez #00179720
--Irvin Josué Pineda Molina #00024420
--Bryan Adilio Rivas López #00113420
--Néstor Esaú Recinos Escobar #00083120

CREATE DATABASE CabinasDeVacunacionCovidDB;

USE CabinasDeVacunacionCovidDB;
SET LANGUAGE us_english

CREATE TABLE EMPLOYEE (
			id INT PRIMARY KEY IDENTITY(1,1),
			name_employee VARCHAR(30) NOT NULL,
			mail VARCHAR(30) UNIQUE NOT NULL,
			type_employee VARCHAR(30) NOT NULL,
			user_employee VARCHAR(30) NOT NULL UNIQUE,
			password_employee VARCHAR(30) NOT NULL,
			address_employee VARCHAR(50) NOT NULL,
			id_municipality INT NOT NULL,	
);

CREATE TABLE MUNICIPALITY (
			id INT PRIMARY KEY IDENTITY(1,1),
			municipality VARCHAR(50) NOT NULL,
			id_departament INT NOT NULL
);

CREATE TABLE DEPARTAMENT (
			id INT PRIMARY KEY IDENTITY(1,1),
			departament VARCHAR(50) NOT NULL
);

CREATE TABLE CABIN (
			id INT PRIMARY KEY IDENTITY(1,1),
			telephone VARCHAR(12) NOT NULL UNIQUE,
			mail VARCHAR(40) UNIQUE NOT NULL,
			address_cabin VARCHAR(50) NOT NULL,
			id_employee INT NOT NULL,	
);

CREATE TABLE APPOINTMENT(
			id INT PRIMARY KEY IDENTITY(1,1),
			date_appointment DATETIME NOT NULL,
			hour_appointment VARCHAR(10) NOT NULL,
			hour_vaccine VARCHAR(10),
			hour_arrival VARCHAR(10),
			dui_patient CHAR(10) NOT NULL,
			id_cabin INT NOT NULL
);

CREATE TABLE PATIENT (
			dui CHAR(10) PRIMARY KEY,
			telephone CHAR(12) NOT NULL UNIQUE,
			name_patient VARCHAR (50) NOT NULL,
			mail VARCHAR(30), 
			address_patient VARCHAR(50) NOT NULL,
			id_institution INT NOT NULL,
			id_chronicdiseases INT NOT NULL,
			id_municipality INT NOT NULL
);


CREATE TABLE INSTITUTION(
			id INT PRIMARY KEY IDENTITY(1,1),
			institution VARCHAR(50) NOT NULL
);

CREATE TABLE CHRONICDISEASES (
			id INT PRIMARY KEY IDENTITY(1,1),
			disease VARCHAR(50) NOT NULL
);

--AÑADIENDO LLAVES FORANEAS--
ALTER TABLE EMPLOYEE ADD CONSTRAINT 
FK_municipality_employee
FOREIGN KEY (id_municipality) REFERENCES MUNICIPALITY (id); 

ALTER TABLE MUNICIPALITY ADD CONSTRAINT 
FK_departament_municipality
FOREIGN KEY (id_departament) REFERENCES DEPARTAMENT (id);

ALTER TABLE CABIN ADD CONSTRAINT 
FK_employee_cabin
FOREIGN KEY (id_employee) REFERENCES EMPLOYEE (id);

ALTER TABLE APPOINTMENT ADD CONSTRAINT 
FK_cabin_appointment
FOREIGN KEY (id_cabin) REFERENCES CABIN (id);

ALTER TABLE APPOINTMENT ADD CONSTRAINT 
FK_patient_appointment 
FOREIGN KEY (dui_patient) REFERENCES PATIENT (dui);

ALTER TABLE PATIENT ADD CONSTRAINT 
FK_institution_patient
FOREIGN KEY (id_institution) REFERENCES INSTITUTION (id);

ALTER TABLE PATIENT ADD CONSTRAINT 
FK_municipality_patient
FOREIGN KEY (id_municipality) REFERENCES MUNICIPALITY (id);

ALTER TABLE PATIENT ADD CONSTRAINT 
FK_disease_patient
FOREIGN KEY (id_chronicdiseases) REFERENCES CHRONICDISEASES(id);

--INGRESANDO DEPARTAMENTOS--
INSERT INTO DEPARTAMENT VALUES('Ahuachapán');
INSERT INTO DEPARTAMENT VALUES('Santa Ana');
INSERT INTO DEPARTAMENT VALUES('Sonsonate');
INSERT INTO DEPARTAMENT VALUES('Chalatenango');
INSERT INTO DEPARTAMENT VALUES('La Libertad');
INSERT INTO DEPARTAMENT VALUES('San Salvador');
INSERT INTO DEPARTAMENT VALUES('Cuscatlán');
INSERT INTO DEPARTAMENT VALUES('La Paz');
INSERT INTO DEPARTAMENT VALUES('Cabañas');
INSERT INTO DEPARTAMENT VALUES('San Vicente');
INSERT INTO DEPARTAMENT VALUES('Usulután');
INSERT INTO DEPARTAMENT VALUES('San Miguel');
INSERT INTO DEPARTAMENT VALUES('Morazán');
INSERT INTO DEPARTAMENT VALUES('La Unión');

--INSERTANDO MUNICIPIOS POR DEPARTAMENTO--

--AUACHAPÁN, ID DPTO. 1--
INSERT INTO MUNICIPALITY VALUES('Ahuachapán',1);
INSERT INTO MUNICIPALITY VALUES('Apaneca',1);
INSERT INTO MUNICIPALITY VALUES('Atiquizaya',1);
INSERT INTO MUNICIPALITY VALUES('Concepción de Ataco',1);
INSERT INTO MUNICIPALITY VALUES('El Refugio',1);
INSERT INTO MUNICIPALITY VALUES('Guaymango',1);
INSERT INTO MUNICIPALITY VALUES('Jujutla',1);
INSERT INTO MUNICIPALITY VALUES('San Francisco Menéndez',1);
INSERT INTO MUNICIPALITY VALUES('San Lorenzo',1);
INSERT INTO MUNICIPALITY VALUES('San Pedro Puxtla',1);
INSERT INTO MUNICIPALITY VALUES('Tacuba',1);
INSERT INTO MUNICIPALITY VALUES('Turín',1);

--SANTA ANA, ID DPTO. 2--
INSERT INTO MUNICIPALITY VALUES('Candelaria de la Frontera',2);
INSERT INTO MUNICIPALITY VALUES('Chalchuapa',2);
INSERT INTO MUNICIPALITY VALUES('Coatepeque',2);
INSERT INTO MUNICIPALITY VALUES('El Congo',2);
INSERT INTO MUNICIPALITY VALUES('El Porvenir',2);
INSERT INTO MUNICIPALITY VALUES('Masahuat',2);
INSERT INTO MUNICIPALITY VALUES('Metapán',2);
INSERT INTO MUNICIPALITY VALUES('San Antonio Pajonal',2);
INSERT INTO MUNICIPALITY VALUES('San Sebastián Salitrillo',2);
INSERT INTO MUNICIPALITY VALUES('Santa Ana',2);
INSERT INTO MUNICIPALITY VALUES('Santa Rosa Guachipilín',2);
INSERT INTO MUNICIPALITY VALUES('Santiago de la Frontera',2);
INSERT INTO MUNICIPALITY VALUES('Texistepeque',2);

--SONSONATE, ID DPTO. 3--
INSERT INTO MUNICIPALITY VALUES('Acajutla',3);
INSERT INTO MUNICIPALITY VALUES('Armenia',3);
INSERT INTO MUNICIPALITY VALUES('Caluco',3);
INSERT INTO MUNICIPALITY VALUES('Cuisnahuat',3);
INSERT INTO MUNICIPALITY VALUES('Izalco',3);
INSERT INTO MUNICIPALITY VALUES('Juayúa',3);
INSERT INTO MUNICIPALITY VALUES('Nahuizalco',3);
INSERT INTO MUNICIPALITY VALUES('Nahulingo',3);
INSERT INTO MUNICIPALITY VALUES('Salcoatitán',3);
INSERT INTO MUNICIPALITY VALUES('San Antonio del Monte',3);
INSERT INTO MUNICIPALITY VALUES('San Julián',3);
INSERT INTO MUNICIPALITY VALUES('Santa Catarina Masahuat',3);
INSERT INTO MUNICIPALITY VALUES('Santa Isabel Ishuatán',3);
INSERT INTO MUNICIPALITY VALUES('Santo Domingo Guzmán',3);
INSERT INTO MUNICIPALITY VALUES('Sonsonate',3);
INSERT INTO MUNICIPALITY VALUES('Sonzacate',3);
 
--CHALATENANGO, ID DPTO. 4--
INSERT INTO MUNICIPALITY VALUES('Agua Caliente',4);
INSERT INTO MUNICIPALITY VALUES('Arcatao',4);
INSERT INTO MUNICIPALITY VALUES('Azacualpa',4);
INSERT INTO MUNICIPALITY VALUES('Chalatenango',4);
INSERT INTO MUNICIPALITY VALUES('Comalapa',4);
INSERT INTO MUNICIPALITY VALUES('Citalá',4);
INSERT INTO MUNICIPALITY VALUES('Concepción Quezaltepeque',4);
INSERT INTO MUNICIPALITY VALUES('Dulce Nombre de María',4);
INSERT INTO MUNICIPALITY VALUES('El Carrizal',4);
INSERT INTO MUNICIPALITY VALUES('El Paraíso',4);
INSERT INTO MUNICIPALITY VALUES('La Laguna',4);
INSERT INTO MUNICIPALITY VALUES('La Palma',4);
INSERT INTO MUNICIPALITY VALUES('La Reina',4);
INSERT INTO MUNICIPALITY VALUES('Las Vueltas',4);
INSERT INTO MUNICIPALITY VALUES('Nueva Concepción',4);
INSERT INTO MUNICIPALITY VALUES('Nueva Trinidad',4);
INSERT INTO MUNICIPALITY VALUES('Nombre de Jesús',4);
INSERT INTO MUNICIPALITY VALUES('Ojos de Agua',4);
INSERT INTO MUNICIPALITY VALUES('Potonico',4);
INSERT INTO MUNICIPALITY VALUES('San Antonio de la Cruz',4);
INSERT INTO MUNICIPALITY VALUES('San Antonio Los Ranchos',4);
INSERT INTO MUNICIPALITY VALUES('San Fernando',4);
INSERT INTO MUNICIPALITY VALUES('San Francisco Lempa',4);
INSERT INTO MUNICIPALITY VALUES('San Francisco Morazán',4);
INSERT INTO MUNICIPALITY VALUES('San Ignacio',4);
INSERT INTO MUNICIPALITY VALUES('San Isidro Labrador',4);
INSERT INTO MUNICIPALITY VALUES('San José Cancasque',4);
INSERT INTO MUNICIPALITY VALUES('San José Las Flores',4);
INSERT INTO MUNICIPALITY VALUES('San Luis del Carmen',4);
INSERT INTO MUNICIPALITY VALUES('San Miguel de Mercedes',4);
INSERT INTO MUNICIPALITY VALUES('San Rafael',4);
INSERT INTO MUNICIPALITY VALUES('Santa Rita',4);
INSERT INTO MUNICIPALITY VALUES('Tejutla',4);

--LA LIBERTAD, DPTO. ID 5--
INSERT INTO MUNICIPALITY VALUES('Antiguo Cuscatlán',5);
INSERT INTO MUNICIPALITY VALUES('Chiltiupán',5);
INSERT INTO MUNICIPALITY VALUES('Ciudad Arce',5);
INSERT INTO MUNICIPALITY VALUES('Colón',5);
INSERT INTO MUNICIPALITY VALUES('Comasagua',5);
INSERT INTO MUNICIPALITY VALUES('Huizúcar',5);
INSERT INTO MUNICIPALITY VALUES('Jayaque',5);
INSERT INTO MUNICIPALITY VALUES('Jicalapa',5);
INSERT INTO MUNICIPALITY VALUES('La Libertad',5);
INSERT INTO MUNICIPALITY VALUES('Santa Tecla',5);
INSERT INTO MUNICIPALITY VALUES('Nuevo Cuscatlán',5);
INSERT INTO MUNICIPALITY VALUES('San Juan Opico',5);
INSERT INTO MUNICIPALITY VALUES('Quezaltepeque',5);
INSERT INTO MUNICIPALITY VALUES('Sacacoyo',5);
INSERT INTO MUNICIPALITY VALUES('San José Villanueva',5);
INSERT INTO MUNICIPALITY VALUES('San Matías',5);
INSERT INTO MUNICIPALITY VALUES('San Pablo Tacachico',5);
INSERT INTO MUNICIPALITY VALUES('Talnique',5);
INSERT INTO MUNICIPALITY VALUES('Tamanique',5);
INSERT INTO MUNICIPALITY VALUES('Teotepeque',5);
INSERT INTO MUNICIPALITY VALUES('Tepecoyo',5);
INSERT INTO MUNICIPALITY VALUES('Zaragoza',5);

--SAN SALVADOR, ID DPTO. 6--
INSERT INTO MUNICIPALITY VALUES('Aguilares',6);
INSERT INTO MUNICIPALITY VALUES('Apopa',6);
INSERT INTO MUNICIPALITY VALUES('Ayutuxtepeque',6);
INSERT INTO MUNICIPALITY VALUES('Cuscatancingo',6);
INSERT INTO MUNICIPALITY VALUES('Ciudad Delgado',6);
INSERT INTO MUNICIPALITY VALUES('El Paisnal',6);
INSERT INTO MUNICIPALITY VALUES('Guazapa',6);
INSERT INTO MUNICIPALITY VALUES('Ilopango',6);
INSERT INTO MUNICIPALITY VALUES('Mejicanos',6);
INSERT INTO MUNICIPALITY VALUES('Nejapa',6);
INSERT INTO MUNICIPALITY VALUES('Panchimalco',6);
INSERT INTO MUNICIPALITY VALUES('Rosario de Mora',6);
INSERT INTO MUNICIPALITY VALUES('San Marcos',6);
INSERT INTO MUNICIPALITY VALUES('San Martín',6);
INSERT INTO MUNICIPALITY VALUES('San Salvador',6);
INSERT INTO MUNICIPALITY VALUES('Santiago Texacuangos',6);
INSERT INTO MUNICIPALITY VALUES('Santo Tomás',6);
INSERT INTO MUNICIPALITY VALUES('Soyapango',6);
INSERT INTO MUNICIPALITY VALUES('Tonacatepeque',6);

--CUSCATLÁN, ID DPTO. 7--
INSERT INTO MUNICIPALITY VALUES('Candelaria',7);
INSERT INTO MUNICIPALITY VALUES('Cojutepeque',7);
INSERT INTO MUNICIPALITY VALUES('El Carmen',7);
INSERT INTO MUNICIPALITY VALUES('El Rosario',7);
INSERT INTO MUNICIPALITY VALUES('Monte San Juan',7);
INSERT INTO MUNICIPALITY VALUES('Oratorio de Concepción',7);
INSERT INTO MUNICIPALITY VALUES('San Bartolomé Perulapía',7);
INSERT INTO MUNICIPALITY VALUES('San Cristobal',7);
INSERT INTO MUNICIPALITY VALUES('San José Guayabal',7);
INSERT INTO MUNICIPALITY VALUES('San Pedro Perulapán',7);
INSERT INTO MUNICIPALITY VALUES('San Rafael Cedros',7);
INSERT INTO MUNICIPALITY VALUES('San Ramón',7);
INSERT INTO MUNICIPALITY VALUES('Santa Cruz Analquito',7);
INSERT INTO MUNICIPALITY VALUES('Santa Cruz Michapa',7);
INSERT INTO MUNICIPALITY VALUES('Suchitoto',7);
INSERT INTO MUNICIPALITY VALUES('Tenancingo',7);

--LA PAZ, ID DPTO. 8--
INSERT INTO MUNICIPALITY VALUES('Cuyultitán',8);
INSERT INTO MUNICIPALITY VALUES('El Rosario',8);
INSERT INTO MUNICIPALITY VALUES('Jerusalén',8);
INSERT INTO MUNICIPALITY VALUES('Mercedes La Ceiba',8);
INSERT INTO MUNICIPALITY VALUES('Olocuilta',8);
INSERT INTO MUNICIPALITY VALUES('Paraiso de Osorio',8);
INSERT INTO MUNICIPALITY VALUES('San Antonio Masahuat',8);
INSERT INTO MUNICIPALITY VALUES('San Emigdo',8);
INSERT INTO MUNICIPALITY VALUES('San Francisco Chinameca',8);
INSERT INTO MUNICIPALITY VALUES('San Juan Nonualco',8);
INSERT INTO MUNICIPALITY VALUES('San Juan Talpa',8);
INSERT INTO MUNICIPALITY VALUES('San Juan Tepezontes',8);
INSERT INTO MUNICIPALITY VALUES('San Luis Talpa',8);
INSERT INTO MUNICIPALITY VALUES('San Luis La Herradura',8);
INSERT INTO MUNICIPALITY VALUES('San Migue Tepezontes',8);
INSERT INTO MUNICIPALITY VALUES('San Pedro Masahuat',8);
INSERT INTO MUNICIPALITY VALUES('San Pedro Nonualco',8);
INSERT INTO MUNICIPALITY VALUES('San Rafael Obrajuelo',8);
INSERT INTO MUNICIPALITY VALUES('Santa María Ostuma',8);
INSERT INTO MUNICIPALITY VALUES('Santiago Nonualco',8);
INSERT INTO MUNICIPALITY VALUES('Tapalhuaca',8);
INSERT INTO MUNICIPALITY VALUES('Zacatecoluca',8);

--CABAÑAS, ID DPTO. 9--
INSERT INTO MUNICIPALITY VALUES('Cinquera',9);
INSERT INTO MUNICIPALITY VALUES('Dolores',9);
INSERT INTO MUNICIPALITY VALUES('Guacotecti',9);
INSERT INTO MUNICIPALITY VALUES('Ilobasco',9);
INSERT INTO MUNICIPALITY VALUES('Jutiapa',9);
INSERT INTO MUNICIPALITY VALUES('San Isidro',9);
INSERT INTO MUNICIPALITY VALUES('Sensuntepeque',9);
INSERT INTO MUNICIPALITY VALUES('Tejutepeque',9);
INSERT INTO MUNICIPALITY VALUES('Victoria',9);

--SAN VICENTE, ID DPTO. 10--
INSERT INTO MUNICIPALITY VALUES('Apastepeque',10);
INSERT INTO MUNICIPALITY VALUES('Guadalupe',10);
INSERT INTO MUNICIPALITY VALUES('San Cayetano Istepeque',10);
INSERT INTO MUNICIPALITY VALUES('San Esteban Catarina',10);
INSERT INTO MUNICIPALITY VALUES('San Idelfonso',10);
INSERT INTO MUNICIPALITY VALUES('San Lorenzo',10);
INSERT INTO MUNICIPALITY VALUES('San Sebastián',10);
INSERT INTO MUNICIPALITY VALUES('San Vicente',10);
INSERT INTO MUNICIPALITY VALUES('Santa Clara',10);
INSERT INTO MUNICIPALITY VALUES('Santo Domingo',10);
INSERT INTO MUNICIPALITY VALUES('Tecoluca',10);
INSERT INTO MUNICIPALITY VALUES('Tepetitán',10);
INSERT INTO MUNICIPALITY VALUES('Verapaz',10);

--USULUTÁN, ID DPTO. 11--
INSERT INTO MUNICIPALITY VALUES('Alegría',11);
INSERT INTO MUNICIPALITY VALUES('Berlín',11);
INSERT INTO MUNICIPALITY VALUES('California',11);
INSERT INTO MUNICIPALITY VALUES('Concepción Batres',11);
INSERT INTO MUNICIPALITY VALUES('El Triunfo',11);
INSERT INTO MUNICIPALITY VALUES('Ereguayquín',11);
INSERT INTO MUNICIPALITY VALUES('Estanzuelas',11);
INSERT INTO MUNICIPALITY VALUES('Jiquilisco',11);
INSERT INTO MUNICIPALITY VALUES('Jucuapa',11);
INSERT INTO MUNICIPALITY VALUES('Jucuarán',11);
INSERT INTO MUNICIPALITY VALUES('Mercedes Umaña',11);
INSERT INTO MUNICIPALITY VALUES('Nueva Granada',11);
INSERT INTO MUNICIPALITY VALUES('Ozatlán',11);
INSERT INTO MUNICIPALITY VALUES('Puerto El Triunfo',11);
INSERT INTO MUNICIPALITY VALUES('San Agustín',11);
INSERT INTO MUNICIPALITY VALUES('San Buenaventura',11);
INSERT INTO MUNICIPALITY VALUES('San Dionisio',11);
INSERT INTO MUNICIPALITY VALUES('San Francisco Javier',11);
INSERT INTO MUNICIPALITY VALUES('Santa Elena',11);
INSERT INTO MUNICIPALITY VALUES('Santa María',11);
INSERT INTO MUNICIPALITY VALUES('Santiago de María',11);
INSERT INTO MUNICIPALITY VALUES('Tecapa',11);
INSERT INTO MUNICIPALITY VALUES('Usulután',11);

--SAN MIGUEL, ID DPTO. 12--
INSERT INTO MUNICIPALITY VALUES('Carolina',12);
INSERT INTO MUNICIPALITY VALUES('Chapeltique',12);
INSERT INTO MUNICIPALITY VALUES('Chinameca',12);
INSERT INTO MUNICIPALITY VALUES('Chirilagua',12);
INSERT INTO MUNICIPALITY VALUES('Ciudad Barrios',12);
INSERT INTO MUNICIPALITY VALUES('Comacarán',12);
INSERT INTO MUNICIPALITY VALUES('El Tránsito',12);
INSERT INTO MUNICIPALITY VALUES('Lolotique',12);
INSERT INTO MUNICIPALITY VALUES('Moncagua',12);
INSERT INTO MUNICIPALITY VALUES('Nueva Guadalupe',12);
INSERT INTO MUNICIPALITY VALUES('Nuevo Edén de San Juan',12);
INSERT INTO MUNICIPALITY VALUES('Quelepa',12);
INSERT INTO MUNICIPALITY VALUES('San Anonio del Mosco',12);
INSERT INTO MUNICIPALITY VALUES('San Gerardo',12);
INSERT INTO MUNICIPALITY VALUES('San Jorge',12);
INSERT INTO MUNICIPALITY VALUES('San Luis de la Reina',12);
INSERT INTO MUNICIPALITY VALUES('San Miguel',12);
INSERT INTO MUNICIPALITY VALUES('San Rafael Oriente',12);
INSERT INTO MUNICIPALITY VALUES('Sesori',12);
INSERT INTO MUNICIPALITY VALUES('Uluazapa',12);

--MORAZÁN, ID DPTO. 13--
INSERT INTO MUNICIPALITY VALUES('Arambala',13);
INSERT INTO MUNICIPALITY VALUES('Cacaopera',13);
INSERT INTO MUNICIPALITY VALUES('Chilanga',13);
INSERT INTO MUNICIPALITY VALUES('Corinto',13);
INSERT INTO MUNICIPALITY VALUES('Delicias de Concepción',13);
INSERT INTO MUNICIPALITY VALUES('El Divisadero',13);
INSERT INTO MUNICIPALITY VALUES('El Rosario',13);
INSERT INTO MUNICIPALITY VALUES('Gualococti',13);
INSERT INTO MUNICIPALITY VALUES('Guatajiagua',13);
INSERT INTO MUNICIPALITY VALUES('Joateca',13);
INSERT INTO MUNICIPALITY VALUES('Jocoaitique',13);
INSERT INTO MUNICIPALITY VALUES('Jocoro',13);
INSERT INTO MUNICIPALITY VALUES('Lolotiquillo',13);
INSERT INTO MUNICIPALITY VALUES('Meanguera',13);
INSERT INTO MUNICIPALITY VALUES('Osicala',13);
INSERT INTO MUNICIPALITY VALUES('Perquín',13);
INSERT INTO MUNICIPALITY VALUES('San Carlos',13);
INSERT INTO MUNICIPALITY VALUES('San Fernando',13);
INSERT INTO MUNICIPALITY VALUES('San Francisco Gotera',13);
INSERT INTO MUNICIPALITY VALUES('San Isidro',13);
INSERT INTO MUNICIPALITY VALUES('San Simón',13);
INSERT INTO MUNICIPALITY VALUES('Sensembra',13);
INSERT INTO MUNICIPALITY VALUES('Sociedad',13);
INSERT INTO MUNICIPALITY VALUES('Torola',13);
INSERT INTO MUNICIPALITY VALUES('Yamabal',13);
INSERT INTO MUNICIPALITY VALUES('Yoloaiquín',13);

--LA UNIÓN, ID DPTO. 14--
INSERT INTO MUNICIPALITY VALUES('Anamorós',14);
INSERT INTO MUNICIPALITY VALUES('Bolívar',14);
INSERT INTO MUNICIPALITY VALUES('Concepción de Oriente',14);
INSERT INTO MUNICIPALITY VALUES('Conchagua',14);
INSERT INTO MUNICIPALITY VALUES('El Carmen',14);
INSERT INTO MUNICIPALITY VALUES('El Sauce',14);
INSERT INTO MUNICIPALITY VALUES('Intipucá',14);
INSERT INTO MUNICIPALITY VALUES('La Unión',14);
INSERT INTO MUNICIPALITY VALUES('Lislique',14);
INSERT INTO MUNICIPALITY VALUES('Meanguera del Golfo',14);
INSERT INTO MUNICIPALITY VALUES('Nueva Esparta',14);
INSERT INTO MUNICIPALITY VALUES('Pasaquina',14);
INSERT INTO MUNICIPALITY VALUES('Porolós',14);
INSERT INTO MUNICIPALITY VALUES('San Alejo',14);
INSERT INTO MUNICIPALITY VALUES('San José',14);
INSERT INTO MUNICIPALITY VALUES('Santa Rosa de Lima',14);
INSERT INTO MUNICIPALITY VALUES('Yayantisque',14);
INSERT INTO MUNICIPALITY VALUES('Yucuaiquín',14);

--GESTORES, UNO POR CABINA--
INSERT INTO EMPLOYEE VALUES('Néstor Recinos','nestor.recinos@gob.sv','Gestor','nestorrecinos_gobsv','Nestor-123','Cantón El Anonal, Casa #5',1);
INSERT INTO EMPLOYEE VALUES('Esaú Escobar','esau.escobar@gob.sv','Gestor','esauescobar_gobsv','Gobierno_2021','Cantón San Juan Buenavista, Pje. #1, Casa #2',22);
INSERT INTO EMPLOYEE VALUES('Irvin Pineda','irvin.pineda@gob.sv','Gestor','irvinpineda_gobsv','Irvin2407','Cantón el Presidio, Pje. #4, Casa #9',40);
INSERT INTO EMPLOYEE VALUES('Josué Molina','josue.molina@gob.sv','Gestor','josuemolina_gobsv','Josue_xD','Cantón El Pinar, Casa #1',66);
INSERT INTO EMPLOYEE VALUES('Brayan Rivas','brayan.rivas@gob.sv','Gestor','brayanrivas_gobsv','Brayan_123','Cantón Las Moras, Casa #12',78);
INSERT INTO EMPLOYEE VALUES('Adilio López','adilio.lopez@gob.sv','Gestor','adiliolopez_gobsv','ALopez_321','Colonia IVU, Casa #12',111);
INSERT INTO EMPLOYEE VALUES('Josué Pérez','josue.perez@gob.sv','Gestor','josueperez_gobsv','Josue!Perez','Cantón Buenavista, Casa #1',125);
INSERT INTO EMPLOYEE VALUES('David Pérez','david.perez@gob.sv','Gestor','davidperez_gobsv','DavidP_12321','Cantón San Sebastián la Zorra, Casa #8',153);
INSERT INTO EMPLOYEE VALUES('Fátima Hernández','fatima.hernandez@gob.sv','Gestor','fatimahernandez_gobsv','Hernandez123','Cantón La Labor, Pje. #3, Casa #5',157);
INSERT INTO EMPLOYEE VALUES('Ana Bonilla','ana.bonilla@gob.sv','Gestor','anabonilla_gobsv','AnaBonilla2001','Cantón Los Pozos, Casa #7',170);
INSERT INTO EMPLOYEE VALUES('Valeria García','valeria.garcia@gob.sv','Gestor','valeriagarcia_gobsv','GarciaVale2020','Cantón San Juan, Pje. 5, Casa #19',176);
INSERT INTO EMPLOYEE VALUES('Erika Recinos','erika.recinos@gob.sv','Gestor','erikarecinos_gobsv','ErikaR_101001','Cantón La Trinidad, Casa #9',215);
INSERT INTO EMPLOYEE VALUES('Karen Oliva','karen.oliva@gob.sv','Gestor','karenoliva_gobsv','KOliva33329','Cantón Guachipilin, Pasaje #7, Casa #1',220);
INSERT INTO EMPLOYEE VALUES('Nicole Orellana','nicole.orellana@gob.sv','Gestor','nicoleorellana','OrellanaNicole_5564','Cantón Loma Larga, Casa #55',252);

--CABINAS UNA POR DEPARTAMENTO--
INSERT INTO CABIN VALUES('+50325416419','ahuachapan@cabina.gob.sv','Parque Central de Ahuachapán',1);
INSERT INTO CABIN VALUES('+50324435675','santaana@cabina.gob.sv','Santa Ana Centro',2);
INSERT INTO CABIN VALUES('+50322324255','sonsonate@cabina.gob.sv','Parque Central de Sonsonate',3);
INSERT INTO CABIN VALUES('+50321232257','chalatenango@cabina.gob.sv','Chalatenango Centro',4);
INSERT INTO CABIN VALUES('+50322106600','lalibertad@cabina.gob.sv','Parque Daniel Hernández, Santa Tecla',5);
INSERT INTO CABIN VALUES('+50325433452','sansalvador@cabina.gob.sv','Hospital El Salvador, San Salvador',6);
INSERT INTO CABIN VALUES('+50325222315','cuscatlan@cabina.gob.sv','Parque Central de Cojutepeque',7);
INSERT INTO CABIN VALUES('+50326654329','lapaz@cabina.gob.sv','Zacatecoluca Centro',8);
INSERT INTO CABIN VALUES('+50323412345','cabanas@cabina.gob.sv','Parque Central de Ilobasco',9);
INSERT INTO CABIN VALUES('+50324321234','sanvicente@cabina.gob.sv','San Vicente Centro',10);
INSERT INTO CABIN VALUES('+50325676539','usulutan@cabina.gob.sv','Parque Central de Usulután',11);
INSERT INTO CABIN VALUES('+50325432343','sanmiguel@cabina.gob.sv','San Miguel Centro',12);
INSERT INTO CABIN VALUES('+50325252525','morazan@cabina.gob.sv','Parque Central de San Francisco Morazán',13);
INSERT INTO CABIN VALUES('+50321212425','launion@cabina.gob.sv','La Unión Centro',14);

--ENFERMEDADES CRÓNICAS--
INSERT INTO CHRONICDISEASES VALUES('Cáncer');
INSERT INTO CHRONICDISEASES VALUES('Insuficiencia Renal');
INSERT INTO CHRONICDISEASES VALUES('Diábetez');
INSERT INTO CHRONICDISEASES VALUES('Autismo');
INSERT INTO CHRONICDISEASES VALUES('VIH-SIDA');
INSERT INTO CHRONICDISEASES VALUES('Lupus');
INSERT INTO CHRONICDISEASES VALUES('Leusemia');
INSERT INTO CHRONICDISEASES VALUES('Ninguna');
INSERT INTO CHRONICDISEASES VALUES('Otra');

--INSTITUCIONES--
INSERT INTO INSTITUTION VALUES('Educación');
INSERT INTO INSTITUTION VALUES('Salud');
INSERT INTO INSTITUTION VALUES('Policía Nacional Civil');
INSERT INTO INSTITUTION VALUES('Fuerza armada');
INSERT INTO INSTITUTION VALUES('Gobierno');
INSERT INTO INSTITUTION VALUES('Periodismo');
INSERT INTO INSTITUTION VALUES('Ninguna');